config/routes.rb
Picgal::Application.routes.draw do
  get "login" => "sessions#new", as: "login"
  post "sessions" => "sessions#create", as: "sessions"
  delete "logout" => "sessions#destroy", as: "logout"

  get "signup" => "users#new", as: "signup"

  get "edit" => "users#edit", as: "edit"

  get "licences" => "pages#licences"

  resources :users #, except: [:new, :create] #, only: [:new, :create, :show, :edit]
  resources :comments
  resources :albums do
    resources :pictures
  end
  resources :pictures#, only: [:show, :edit, :destroy]
  resources :groups

  get "groups/:id/join" => "groups#join", as: "join_group"
  put "groups/:id/join" => "groups#join", as: "join_group"

  root to: "pages#home"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, :polymorphic => true
  belongs_to :user
  attr_accessible :commentable_id, :commentable_type, :content, :user_id
  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(params[:comment])
    @comment.user = current_user

    if @comment.save
      flash[:notice] = 'Comment posted.'
      redirect_to(session[:return_to] || root_path)
      session[:return_to] = nil
    else
      flash[:notice] = 'Error: Comment could not be posted.'
      render :action => 'new'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to(session[:return_to] || root_path)
    session[:return_to] = nil
  end

  def new
    @comment = Comment.new
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update_attributes(params[:comment])
      flash[:notice] = 'Comment edited.'
      redirect_to(session[:return_to] || root_path)
      session[:return_to] = nil
    else
      flash[:notice] = 'Error: Comment could not be edited.'
      render action: "edit"
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def is_owner_or_author?(comment)
    return true if current_user == comment.user
    return comment.commentable_type == User.to_s && comment.commentable == current_user
  end
end

app/views/comments/_comment.html.erb
<div class="comment">
  <p>
    <b><%= link_to comment.user.name, user_path(comment.user.name) %></b> wrote
    <% if comment.created_at > Date.yesterday.end_of_day %>
        <i>today at <%= comment.created_at.strftime("%H:%M:%S") %></i>
    <% elsif comment.created_at > Date.yesterday.beginning_of_day %>
        <i>yesterday at <%= comment.created_at.strftime("%H:%M:%S") %></i>
    <% else %>
        on <i><%= comment.created_at %></i>:
    <% end %>
    <% if is_owner_or_author?(comment) %>
        <%= link_to "[e]", edit_comment_path(comment) %>
        <%= link_to "[x]", comment, :confirm => 'Delete comment?', :method => :delete %>
    <% end %>
    <br>
    <%= comment.content %>
</p>
</div>

app/views/comments/_form.html.erb
<% if user_signed_in? %>
    <%= form_for(@comment) do |f| %>
        <% if @comment.errors.any? %>
            <ul>
              <% @comment.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
        <% end %>
        <%= f.hidden_field :commentable_id %>
        <%= f.hidden_field :commentable_type %>
        <p>
          <%= f.text_area :content %>
        </p>
        <p>
          <%= f.submit %>
        </p>
    <% end %>
<% else %>
    <p>
      <%= link_to "Log in", login_path %> or
      <%= link_to "sign up", signup_path %> first to write a comment.
    </p>
<% end %>

app/views/comments/edit.html.erb
<h2>Edit comment</h2>
<%= render "form" %>