config/routes.rb
Picgal::Application.routes.draw do
  get "login" => "sessions#new", as: "login"
  post "sessions" => "sessions#create", as: "sessions"
  delete "logout" => "sessions#destroy", as: "logout"

  get "signup" => "users#new", as: "signup"

  get "edit" => "users#edit", as: "edit"

  get "licences" => "pages#licences"

  resources :users #, except: [:new, :create] #, only: [:new, :create, :show, :edit]
  resources :comments
  resources :albums do
    resources :pictures
  end
  resources :pictures#, only: [:show, :edit, :destroy]
  resources :groups

  get "groups/:id/join" => "groups#join", as: "join_group"
  put "groups/:id/join" => "groups#join", as: "join_group"

  root to: "pages#home"

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :comments, :as => :commentable, :dependent => :destroy
  attr_accessible :name, :description, :founder
  validates :name, presence: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def new
    @group = Group.new
  end

  def create
    @group = Group.new(params[:group])
    @group.founder = current_user.id
    # Gründer heißt nicht automatisch auch Mitglied! So kann man als Admin Gruppen vorgeben.

    if @group.save
      flash[:notice] = 'Group founded. Join if you want to take part in it!'
      redirect_to(session[:return_to] || root_path)
      session[:return_to] = nil
    else
      flash[:notice] = 'Error: Group could not be founded.'
      render :action => 'new'
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update_attributes(params[:group])
      redirect_to group_path(@group), notice: "Group updated"
    else
      render action: "edit"
    end
  end

  def show
    @group = Group.find(params[:id])
    @users = @group.users

    # Das geht sicher auch einfacher, aber eleganter habe ich es leider nicht geschafft.
    @comments = Comment.find_all_by_commentable_id_and_commentable_type(@group.id, @group.class).reverse
    @comment = Comment.new(:commentable_id => @group.id)
    @comment.commentable_type = @group.class

    # Wie oben.
    @pictures = Picture.find_all_by_album_id(Album.find_all_by_user_id(@users)).last(10).reverse
    session[:return_to] = request.env["REQUEST_URI"]
  end

  def index
    @groups = Group.all
  end

  def join
    @group = Group.find(params[:id])
    @user = current_user
    @membership = GroupsUsers.new(:group_id => @group.id, :user_id => @user.id)

    if @membership.save
      redirect_to(session[:return_to] || root_path, notice: "You joined. Welcome :)")
      session[:return_to] = nil
    else
      redirect_to group_path(@group), notice: "Error: Could not join group"
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to(session[:return_to] || root_path)
    session[:return_to] = nil
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
  def is_founder?(group)
      return current_user.id == group.founder
  end
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
    <% if @group.errors.any? %>
        <ul>
          <% @group.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
        </ul>
    <% end %>
    <p>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :description %>
      <%= f.text_area :description %>
    </p>
    <p><%= f.submit %></p>
<% end %>

app/views/groups/_group.html.erb
<li>
  <%= link_to group.name, group_path(group) %>
  (<%= group.users.count %> members with a total of
  <%= Album.find_all_by_user_id(group.users).count %> galleries)
  <% if user_signed_in? && is_founder?(group) %>
    <%= link_to "[edit]", edit_group_path(group) %>
    <%= link_to "[delete]", group, :confirm => 'Really disband group?', :method => :delete %>
  <% end %>
</li>

app/views/groups/edit.html.erb
<h2>Edit group</h2>
<%= render "form" %>

app/views/groups/index.html.erb
<h2>Groups</h2>
<ul>
  <%= render @groups %>
</ul>
<% if user_signed_in? %>
    <%= link_to "Found a new group", new_group_path %>
<% end %>

app/views/groups/new.html.erb
<h2>New group</h2>
<%= render "form" %>

app/views/groups/show.html.erb
<% if @group %>
    <h2><%= @group.name %> - group profile</h2>
    <% if user_signed_in? %>
        <%= link_to "Join group", join_group_path %>
        <% if is_founder?(@group) %>
            | <%= link_to "Edit group", edit_group_path(@group) %>
        <% end %>
    <% end %>
    <p><b>Founder:</b>
      <!-- Gehoert eigentlich den Controller... Ich habe '@group.founder.name' versucht, habe aber die Foreign-Key-Beziehung nicht hinbekommen. -->
      <%= link_to User.find(@group.founder).name, user_path(User.find(@group.founder).name) %>
    </p>
    <p>
      <b>Description:</b>
      <%= @group.description %>
    </p>
    <p>
        <b>Members:</b>
        <ul>
          <%= render @users %>
        </ul>
    </p>
    <p>
      <b>Members' latest additions:</b>
      <ul>
        <%= render @pictures %>
      </ul>
    </p>
    <hr/>
    <%= render @comments %>
    <%= render :partial => 'comments/form' %>
<% else %>
    We're sorry, group '<%= @group %>' could not be found.
<% end %>