config/routes.rb
Picgal::Application.routes.draw do
  get "login" => "sessions#new", as: "login"
  post "sessions" => "sessions#create", as: "sessions"
  delete "logout" => "sessions#destroy", as: "logout"

  get "signup" => "users#new", as: "signup"

  get "edit" => "users#edit", as: "edit"

  get "licences" => "pages#licences"

  resources :users #, except: [:new, :create] #, only: [:new, :create, :show, :edit]
  resources :comments
  resources :albums do
    resources :pictures
  end
  resources :pictures#, only: [:show, :edit, :destroy]
  resources :groups

  get "groups/:id/join" => "groups#join", as: "join_group"
  put "groups/:id/join" => "groups#join", as: "join_group"

  root to: "pages#home"

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :album
  has_one :user, :through => :albums
  has_many :comments, :as => :commentable, :dependent => :destroy
  attr_accessible :album_id, :description, :licence, :name, :source, :image, :remote_image_url
  validates :name, presence: true
  validates :licence, presence: true
  mount_uploader :image, ImageUploader
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def new
    @picture = Picture.new
    @album = Album.find(params[:album_id])
  end

  def create
    @picture = Picture.new(params[:picture])
    @picture.album = Album.find(params[:album_id])

    if @picture.save
      redirect_to(session[:return_to] || root_path, notice: "Picture uploaded")
      session[:return_to] = nil
    else
      render "new"
    end
  end

  def edit
    @picture = Picture.find(params[:id])
  end

  def show
    @picture = Picture.find(params[:id])
    @comments = Comment.find_all_by_commentable_id_and_commentable_type(@picture.id,@picture.class).reverse
    @comment = Comment.new(:commentable_id => @picture.id)
    @comment.commentable_type = @picture.class

    session[:return_to] = request.env["REQUEST_URI"]
  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy

    redirect_to(session[:return_to] || root_path)
    session[:return_to] = nil
  end

  def update
    @picture = Picture.find(params[:id])
    if @picture.update_attributes(params[:picture])
      flash[:notice] = 'Picture edited.'
      redirect_to(session[:return_to] || root_path)
      session[:return_to] = nil
    else
      flash[:notice] = 'Error: Picture could not be edited.'
      render action: "edit"
    end
  end

end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.erb
<%= form_for [@album, @picture] do |f| %>
    <% if @picture.errors.any? %>
        <ul>
          <% @picture.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
        </ul>
    <% end %>
    <%= f.hidden_field :album_id %>
    <p>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :licence, "Default licence" %>
      <%= f.collection_select(:licence, Licence.all, :id, :name,) %>
      <%= link_to "[?]", licences_path %>
    </p>
    <p>
      <%= f.label "Local picture" %>
      <%= f.file_field :image %>
    </p>
    <p>
      <%= f.label "URL of picture" %>
      <%= f.text_field :remote_image_url %>
    </p>
    <p>
      <%= f.label :source %>
      <%= f.text_field :source %>
    </p>
    <p>
      <%= f.label :description %>
      <br/>
      <%= f.text_area :description %>
    </p>
    <p>
      <%= f.submit "Upload Picture" %>
    </p>
<% end %>

app/views/pictures/_picture.html.erb
<div class="picture">
  <%= link_to image_tag(picture.image_url(:thumb)), picture_path(picture) %>
  <div class="name">
    <%= link_to picture.name, picture_path(picture) %>
    [<%= picture.comments.count %> comments]
    <br/>
    <i><%= sanitize(truncate(picture.description),:length => 150) %></i>
  </div>
  <div class="actions">
    <%= link_to "edit", edit_picture_path(picture) %> |
    <%= link_to "delete", picture, :confirm => 'Really delete picture?', :method => :delete %>
  </div>
</div>

app/views/pictures/edit.html.erb
<h2>Edit picture</h2>
<%= render "form" %>

app/views/pictures/new.html.erb
<h2>Upload picture</h2>
<%= render "form" %>

app/views/pictures/show.html.erb
<h2><%= @picture.name %></h2>
<%= image_tag @picture.image_url if @picture.image? %>
<br/>
<p>Name: <%= @picture.name %></p>
<p>Description: <%= @picture.description %></p>
<p>Source: <%= @picture.source %></p>
<p>Licence: <%= Licence.find_by_id(@picture.licence).name %></p>
<p>Date: <%= @picture.created_at %></p>
<%= link_to "...return to gallery '" + @picture.album.name + "'", album_path(@picture.album) %>
<hr/>
<%= render @comments %>
<%= render :partial => 'comments/form' %>