config/routes.rb
Picgal::Application.routes.draw do
  get "login" => "sessions#new", as: "login"
  post "sessions" => "sessions#create", as: "sessions"
  delete "logout" => "sessions#destroy", as: "logout"

  get "signup" => "users#new", as: "signup"

  get "edit" => "users#edit", as: "edit"

  get "licences" => "pages#licences"

  resources :users #, except: [:new, :create] #, only: [:new, :create, :show, :edit]
  resources :comments
  resources :albums do
    resources :pictures
  end
  resources :pictures#, only: [:show, :edit, :destroy]
  resources :groups

  get "groups/:id/join" => "groups#join", as: "join_group"
  put "groups/:id/join" => "groups#join", as: "join_group"

  root to: "pages#home"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Picgal</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div id="container">
      <div id="header">
        <h1><%= link_to "PicGal", root_path %></h1>
      </div>
      <div id="content">
        <% if flash[:notice] %>
            <p id="notice">
                <%= flash[:notice] %>
            </p>
        <% end %>
        <p>
          <%= yield %>
        </p>
      </div>
    </div>
    <div id="footer">
      <% if user_signed_in? %>
          Logged in as:
          <%= link_to current_user.name, user_path(current_user.name) %> |
          <%= link_to "Logout", logout_path, method: :delete %> |
          <%= link_to "Edit profile", edit_path %> |
          <%= link_to "New album", new_album_path %> |
      <% else %>
          <%= link_to "Login", login_path %> |
          <%= link_to "Sign up", signup_path %> |
      <% end %>
      <%=  link_to "Members", users_path %> |
      <%=  link_to "Groups", groups_path %> |
      <%=  link_to "Licences", licences_path %> |
      <%=  link_to "Support/FAQ", "http://lmgtfy.com/?q=picgal+help" %> <!-- Ich war im First-Level-Support, vertrau mir. -->
    </div>
</body>
</html>